# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

SignalConfigs:
  # Multimedia: category 3
  # Video decode
  # Default decode
  - SigId: "0x0001"
    Category: "0x03"
    Name: "URM_SIG_VIDEO_DECODE"
    Enable: true
    TargetsEnabled: ["qcs9100"]
    Permissions: ["third_party", "system"]
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEMORY", Values: [3, 1073741824]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEMORY", Values: [4, 519430400]}
      - {ResCode: "RES_CGRP_MIN_MEMORY", Values: [4, 119430400]}
      - {ResCode: "RES_SCALING_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [1267200]}
      - {ResCode: "RES_SCALING_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [1267200]}

  # Video decode
  # Decode 5+ concurrent sessions
  - SigId: "0x0001"
    Category: "0x03"
    SigType: 5
    Name: "URM_SIG_VIDEO_DECODE"
    Enable: true
    TargetsEnabled: ["qcs9100"]
    Permissions: ["third_party", "system"]
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEMORY", Values: [3, 1073741824]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEMORY", Values: [4, 519430400]}
      - {ResCode: "RES_CGRP_MIN_MEMORY", Values: [4, 119430400]}
      - {ResCode: "RES_SCALING_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [1536000]}
      - {ResCode: "RES_SCALING_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [1536000]}

  # Video decode
  # Decode 20+ concurrent sessions
  - SigId: "0x0001"
    Category: "0x03"
    SigType: 20
    Name: "URM_SIG_VIDEO_DECODE"
    Enable: true
    TargetsEnabled: ["qcs9100"]
    Permissions: ["third_party", "system"]
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEMORY", Values: [3, 1073741824]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEMORY", Values: [4, 519430400]}
      - {ResCode: "RES_CGRP_MIN_MEMORY", Values: [4, 119430400]}

  # Camera preview
  # Default preview - 30fps
  - SigId: "0x0002"
    Category: "0x03"
    Name: "URM_SIG_CAMERA_PREVIEW"
    Enable: true
    TargetsEnabled: ["qcs9100"]
    Permissions: ["third_party", "system"]
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEMORY", Values: [3, 1073741824]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEMORY", Values: [4, 519430400]}
      - {ResCode: "RES_CGRP_MIN_MEMORY", Values: [4, 119430400]}
      - {ResCode: "RES_SCALING_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [1267200]}
      - {ResCode: "RES_SCALING_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [1267200]}

  # camera encode
  # Default encode - 30fps
  - SigId: "0x0003"
    Category: "0x03"
    Name: "URM_SIG_CAMERA_ENCODE"
    Enable: true
    TargetsEnabled: ["qcs9100"]
    Permissions: ["third_party", "system"]
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEMORY", Values: [3, 1073741824]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEMORY", Values: [4, 519430400]}
      - {ResCode: "RES_CGRP_MIN_MEMORY", Values: [4, 119430400]}
      - {ResCode: "RES_SCALING_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [1267200]}
      - {ResCode: "RES_SCALING_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [1267200]}

  # camera encode multi-stream
  # encode (0-12 streams)
  - SigId: "0x0004"
    Category: "0x03"
    Name: URM_SIG_CAMERA_ENCODE_MULTI_STREAMS
    Enable: true
    TargetsEnabled: ["qcs9100"]
    Permissions: ["third_party", "system"]
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEMORY", Values: [3, 1073741824]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEMORY", Values: [4, 519430400]}
      - {ResCode: "RES_CGRP_MIN_MEMORY", Values: [4, 119430400]}
      - {ResCode: "RES_SCALING_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [1267200]}
      - {ResCode: "RES_SCALING_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [1267200]}

# camera encode multi-stream
# encode (12+ streams)
  - SigId: "0x0004"
    Category: "0x03"
    SigType: 12
    Name: URM_SIG_CAMERA_ENCODE_MULTI_STREAMS
    Enable: true
    TargetsEnabled: ["qcs9100"]
    Permissions: ["third_party", "system"]
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEMORY", Values: [3, 1073741824]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEMORY", Values: [4, 519430400]}
      - {ResCode: "RES_CGRP_MIN_MEMORY", Values: [4, 119430400]}
