SignalConfigs:
  - SigId: "0x00000001"
    Type: 0
    Name: URM_APP_OPEN
    Enable: true
    Permissions: ["system", "third_party"]
    Resources:
      - {ResCode: "0x00090002", ResInfo: "0x00000000", Values: [2, 0,1,2,3]}
      - {ResCode: "0x00090011", ResInfo: "0x00000000", Values: [4, -20]}
