SignalConfigs:
  - SigId: "0x0001"
    Category: "0x01"
    Name: URM_APP_OPEN
    Enable: true
    Permissions: ["system", "third_party"]
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
